# ██╗░░░██╗░█████╗░███╗░░██╗██╗██╗░░░░░██╗░░░░░░█████╗░    ████████╗░██╗░░░░░░░██╗███████╗░█████╗░██╗░░██╗░██████╗
# ██║░░░██║██╔══██╗████╗░██║██║██║░░░░░██║░░░░░██╔══██╗    ╚══██╔══╝░██║░░██╗░░██║██╔════╝██╔══██╗██║░██╔╝██╔════╝
# ╚██╗░██╔╝███████║██╔██╗██║██║██║░░░░░██║░░░░░███████║    ░░░██║░░░░╚██╗████╗██╔╝█████╗░░███████║█████═╝░╚█████╗░
# ░╚████╔╝░██╔══██║██║╚████║██║██║░░░░░██║░░░░░██╔══██║    ░░░██║░░░░░████╔═████║░██╔══╝░░██╔══██║██╔═██╗░░╚═══██╗
# ░░╚██╔╝░░██║░░██║██║░╚███║██║███████╗███████╗██║░░██║    ░░░██║░░░░░╚██╔╝░╚██╔╝░███████╗██║░░██║██║░╚██╗██████╔╝
# ░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚══╝╚═╝╚══════╝╚══════╝╚═╝░░╚═╝    ░░░╚═╝░░░░░░╚═╝░░░╚═╝░░╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░

reload:
  message: "&7[&6&lVT&7] &aReloaded Vanilla Tweaks Config!"


packs:
  # Enable a pack by marking "enabled" as "true"
  # If a pack is not enabled, none of its effects will happen.

  # Player Head Drops
  # A player will drop their head when killed by another player. The item displays who the killer is.
  player-head-drops:
    enabled: false
    display-killer: true

  # Double Shulker Shells
  # Makes all shulkers drop 2 shells.
  double-shulker-shells:
    enabled: false

  # Dragon Drops
  # Makes the Ender Dragon drop a dragon egg and elytra on death.
  dragon-drops:
    enabled: false

  # Silence Mobs
  # Adds the ability to silence mobs using a name tag. 'Silence Me'; 'Silence me'; 'silence me'; 'silence_me'; are all acceptable names.
  silence-mobs:
    enabled: false

  # Anti Creeper Grief
  # Prevents creepers from blowing up, blocks and players do not take damage.
  anti-creeper-grief:
    enabled: false

  # Anti Enderman Grief
  # Prevents endermen from picking up blocks.
  anti-enderman-grief:
    enabled: false

  # Anti Creeper Grief
  # Prevents ghasts from blowing up blocks.
  anti-ghast-grief:
    enabled: false

  # Nether Portal Coords
  # Adds a command that calculates where a nether portal must be placed in the other dimension. Useful for syncing up nether portals.
  # Command: /portal
  nether-portal-coords:
    enabled: false

  # Coords HUD
  # Adds information to your actionbar. XYZ Coords and a 24hr clock.
  # Command: /ch toggle
  coords-hud:
    enabled: false

  # Spectator Night Vision
  # Easily toggle night vision when in spectator.
  # Command: /nv
  spectator-night-vision:
    enabled: false

  # Spectator Conduit Power
  # Easily toggle conduit power when in spectator.
  # Command: /cp
  spectator-conduit-power:
    enabled: false

  # Kill Empty Boats
  # Adds an admin command to kill all boats without passengers.
  # Command: /killboats
  kill-boats:
    enabled: false

  # More Mob Heads
  # Adds a chance to receive a mob head upon killing it.
  more-mob-heads:
    enabled: true

config:
  version: 1